=== proudcommerce/OXArchive/out/basic/src/gui/gui.xsd
<?xml version="1.0" encoding="ISO-8859-15" standalone="yes"?>
<xs:schema id="OXIDGui" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="gui">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="theme" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="color" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
            <xs:attribute name="title" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>

        <xs:element name="gif" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="color" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="tpl" type="xs:string" use="required" />
            <xs:attribute name="file" type="xs:string" use="required" />
            <xs:attribute name="const" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>

        <xs:element name="css" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="group" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="tpl" type="xs:string" />
            <xs:attribute name="file" type="xs:string" />
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="color">
    <xs:complexType>
      <xs:attribute name="index" type="xs:int"/>
      <xs:attribute name="color" type="xs:string" />
      <xs:attribute name="const" type="xs:string"/>
      <xs:attribute name="title" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="color" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="group" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="title" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== proudcommerce/OXArchive/out/basic/src/gui/gui.xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<gui xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gui.xsd">

    <theme id="ce" title="Default">
        <color index="0" color="#fff" />
        <color index="1" color="#f0f0f0" />
        <color index="2" color="#969696" />
        <color index="3" color="#424c56" />
        <color index="4" color="#000" />
        <color index="5" color="#fdf3eb" />
        <color index="6" color="#507A1F" />
        <color index="7" color="#8CB52D" />
    </theme>

    <theme id="pe" title="Default">
        <color index="0" color="#fff" />
        <color index="1" color="#f0f0f0" />
        <color index="2" color="#969696" />
        <color index="3" color="#424c56" />
        <color index="4" color="#000" />
        <color index="5" color="#fdf3eb" />
        <color index="6" color="#ff4f00" />
        <color index="7" color="#ff1900" />
    </theme>

    <theme id="ee" title="Default">
        <color index="0" color="#fff" />
        <color index="1" color="#f0f0f0" />
        <color index="2" color="#969696" />
        <color index="3" color="#424c56" />
        <color index="4" color="#000" />
        <color index="5" color="#d4e2eb" />
        <color index="6" color="#015b9b" />
        <color index="7" color="#004b80" />
    </theme>

    <theme id="01" title="Gray">
        <color index="0" color="#fff" />
        <color index="1" color="#f0f0f0" />
        <color index="2" color="#969696" />
        <color index="3" color="#424c56" />
        <color index="4" color="#000" />
        <color index="5" color="#CCCCCC" />
        <color index="6" color="#666666" />
        <color index="7" color="#333333" />
    </theme>

    <theme id="02" title="Green">
        <color index="0" color="#fff" />
        <color index="1" color="#f0f0f0" />
        <color index="2" color="#969696" />
        <color index="3" color="#424c56" />
        <color index="4" color="#000" />
        <color index="5" color="#f0fce8" />
        <color index="6" color="#75e72f" />
        <color index="7" color="#4bc202" />
    </theme>


    <!-- Faux collumns background -->
    <gif tpl="bd.tpl.gif" file="bg/bd.gif" const="oxFauxColBg">
        <color const="0" color="oxLeftBg" />
        <color const="1" color="oxLeftBr" />
        <color const="2" color="oxBodyBg" />
        <color const="3" color="oxRightBr" />
        <color const="4" color="oxRightBg" />
    </gif>

    <!-- Css sprite arrows-->
    <gif tpl="oxid.tpl.gif" file="bg/oxid.gif" const="oxSprite">
        <color const="0" color="oxHeaderBoxHdIco" />
        <color const="1" color="oxHeaderBoxHdOpenIco" />
        <color const="2" color="oxHeaderBoxDdIco" />
        <color const="3" color="oxHeaderBoxDdHlIco" />
        <color const="4" color="oxHeaderBoxBdIco" />
        <color const="5" color="oxHeaderBarCatsIco" />
        <color const="6" color="oxHeaderBarCatsOpenIco" />

        <color const="7" color="oxLeftTreeIco" />
        <color const="8" color="oxLeftTreeOpenIco" />
        <color const="9" color="oxLeftTreeActIco" />

        <color const="10" color="oxLeftInfoIco" />
        <color const="11" color="oxProductActionsIco" />

        <color const="12" color="oxBodyPrevNextIco" />
        <color const="13" color="oxBodyPrevNextDownIco" />

        <color const="14" color="oxBodyRightIco" />
        <color const="15" color="oxRightRightIco" />
    </gif>

    <!-- Css buttons -->
    <gif tpl="buttons.tpl.gif" file="bg/buttons.gif" const="oxButtons">
        <color const="0" color="oxButtonBr" />
        <color const="1" color="oxButtonBg" />
        <color const="2" color="oxButtonIco" />
    </gif>

    <!-- The style -->
    <css tpl="oxid.tpl.css" file="oxid.css">

        <group title="GUI_GROUP_HEADER">
            <color const="oxHeaderBg" color="0" title="GUI_BACKGROUND_COLOR" />
            <color const="oxHeaderBr" color="0" title="GUI_BORDER_COLOR" />
            <group title="GUI_GROUP_HEADER_BOXES">
                <group title="GUI_GROUP_HEADER_BOXES_GENERAL">
                    <color const="oxHeaderBoxHdBg" color="2" title="GUI_HEAD_BACKGROUND_COLOR" />
                    <color const="oxHeaderBoxHdCl" color="0" title="GUI_HEAD_TEXT_COLOR" />
                    <color const="oxHeaderBoxHdIco" color="0" title="GUI_HEAD_ICON" />
                    <color const="oxHeaderBoxBdBg" color="1" title="GUI_BACKGROUND_COLOR" />
                    <color const="oxHeaderBoxBdCl" color="4" title="GUI_TEXT_COLOR" />
                    <color const="oxHeaderBoxBdIco" color="3" title="GUI_ICON" />
                </group>
                <group title="GUI_GROUP_HEADER_BOXES_BASKET">
                    <color const="oxHeaderBoxBasketHdBg" color="6" title="GUI_HEAD_BACKGROUND" />
                    <color const="oxHeaderBoxBasketHdCl" color="0" title="GUI_HEAD_TEXT_COLOR" />
                    <color const="oxHeaderBoxBasketBdBg" color="5" title="GUI_BODY_BACKGROUND" />
                    <color const="oxHeaderBoxBasketBdCl" color="4" title="GUI_BODY_TEXT_COLOR" />
                    <group title="GUI_GROUP_HEADER_BOXES_DROPDOWN">
                        <color const="oxHeaderBoxBasketOpenBg" color="2" title="GUI_HEAD_BACKGROUND" />
                        <color const="oxHeaderBoxBasketOpenCl" color="0" title="GUI_HEAD_TEXT_COLOR" />

                        <color const="oxHeaderBoxBasketDdBg" color="1" title="GUI_DROPDOWN_BACKGROUND" />
                        <color const="oxHeaderBoxBasketDdCl" color="4" title="GUI_DROPDOWN_TEXT_COLOR" />

                        <color const="oxHeaderBoxBasketDdHlBg" color="2" title="GUI_DROPDOWN_HL_BACKGROUND" />
                        <color const="oxHeaderBoxBasketDdHlCl" color="0" title="GUI_DROPDOWN_HL_TEXT_COLOR" />
                    </group>
                </group>
                <group title="GUI_GROUP_HEADER_BOXES_DROPDOWN">
                    <color const="oxHeaderBoxHdOpenBg" color="7" title="GUI_HEAD_BACKGROUND" />
                    <color const="oxHeaderBoxHdOpenCl" color="0" title="GUI_HEAD_TEXT_COLOR" />
                    <color const="oxHeaderBoxHdOpenIco" color="0" title="GUI_HEAD_ICON" />

                    <color const="oxHeaderBoxDdBg" color="5" title="GUI_DROPDOWN_BACKGROUND" />
                    <color const="oxHeaderBoxDdCl" color="3" title="GUI_DROPDOWN_TEXT_COLOR" />
                    <color const="oxHeaderBoxDdIco" color="4" title="GUI_DROPDOWN_ICON" />

                    <color const="oxHeaderBoxDdHlBg" color="7" title="GUI_DROPDOWN_HL_BACKGROUND" />
                    <color const="oxHeaderBoxDdHlCl" color="0" title="GUI_DROPDOWN_HL_TEXT_COLOR" />
                    <color const="oxHeaderBoxDdHlIco" color="0" title="GUI_DROPDOWN_HL_ICON" />
                </group>
            </group>

            <group title="GUI_GROUP_HEADER_LINKS">
                <color const="oxHeaderBarLinksBg" color="6" title="GUI_BACKGROUND" />
                <color const="oxHeaderBarLinksSingleBg" color="7" title="GUI_SINGLE_BACKGROUND" />
                <color const="oxHeaderBarLinksCl" color="0" title="GUI_TEXT_COLOR" />
                <color const="oxHeaderBarLinksHlCl" color="1" title="GUI_HIGHLITED_COLOR" />
            </group>

            <group title="GUI_GROUP_HEADER_CATEGORIES">
                <color const="oxHeaderBarCatsBg" color="7" title="GUI_BACKGROUND" />
                <color const="oxHeaderBarCatsCl" color="0" title="GUI_TEXT_COLOR" />
                <color const="oxHeaderBarFixedBg" color="7" title="GUI_FIXED_BACKGROUND" />
                <color const="oxHeaderBarFixedCl" color="0" title="GUI_FIXED_TEXT_COLOR" />
                <color const="oxHeaderBarFixedHlBg" color="6" title="GUI_FIXED_HL_BACKGROUND" />
                <color const="oxHeaderBarFixedHlCl" color="0" title="GUI_FIXED_HL_TEXT_COLOR" />
                <color const="oxHeaderBarCatsIco" color="0" title="GUI_ICON" />
                <color const="oxHeaderBarCatsOpenBg" color="6" title="GUI_DROPDOWN_BACKGROUND" />
                <color const="oxHeaderBarCatsOpenCl" color="0" title="GUI_DROPDOWN_TEXT_COLOR" />
                <color const="oxHeaderBarCatsOpenIco" color="0" title="GUI_DROPDOWN_ICON" />
                <color const="oxHeaderBarCatsOpenHlBg" color="7" title="GUI_DROPDOWN_HL_BACKGROUND" />
                <color const="oxHeaderBarCatsOpenHlCl" color="0" title="GUI_DROPDOWN_HL_TEXT_COLOR" />
            </group>
        </group>
        <group title="GUI_GROUP_BUTTONS">
            <color color="7" const="oxButtonIco" title="GUI_ICON" />
            <color color="7" const="oxButtonBr" title="GUI_BORDER" />
            <color color="7" const="oxButtonBg" title="GUI_BACKGROUND" />
            <color color="0" const="oxButtonCl" title="GUI_TEXT_COLOR" />
        </group>
        <group title="GUI_GROUP_FOOTER">
            <color const="oxFooterBg" color="0" title="GUI_BOTTOM_BACKGROUND" />
            <color const="oxFooterBr" color="0" title="GUI_BOTTOM_BORDER" />
            <color const="oxFooterCl" color="4" title="GUI_BOTTOM_TEXT_COLOR" />
            <color const="oxFooterCopyBg" color="7" title="GUI_COPY_BACKGROUND" />
            <color const="oxFooterCopyCl" color="0" title="GUI_COPY_TEXT_COLOR" />
            <color const="oxFooterShopBg" color="0" title="GUI_SHOP_BACKGROUND" />
            <color const="oxFooterShopCl" color="2" title="GUI_SHOP_TEXT_COLOR" />
        </group>
        <group title="GUI_GROUP_LEFT">
            <color const="oxLeftBg" color="5" title="GUI_BACKGROUND" />
            <color const="oxLeftBr" color="6" title="GUI_BORDER" />
            <color const="oxLeftHdBg" color="6" title="GUI_HEAD_BACKGROUND" />
            <color const="oxLeftHdCl" color="0" title="GUI_HEAD_TEXT_COLOR" />
